name: "Build & Publish"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: "Build & Test"
    runs-on:
      - ubuntu-latest
    env:
      GRADLE_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dorg.gradle.parallel=true -Dorg.gradle.console=plain -Dorg.gradle.logging.stacktrace=all"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
          # Comment out when you are upgrading gradle in a branch and doing tons of commits you would need to test.
          # cache-read-only: false
      - name: "Assemble jar"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --info --parallel
      - name: "Compile tests"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileTest --info --parallel
      - name: "Run checks"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - name: "Publish Test Report"
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          require_tests: true
      - name: Publish checkstyle report
        if: failure()
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/build/reports/**/*.xml'
      - name: Publish spotbugs report
        if: failure()
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/build/reports/**/*.xml'
      - name: "Test if publishing works"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal --info
      - name: "Tag release"
        if: github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: tagRelease --info
